export const incidentTypes = [
  "ACOSO LABORAL",
  "CONFLICTO DE INTERESES",
  "DAÑOS AL MEDIO AMBIENTE",
  "VIOLACION DE LAS LEYES",
  "INCUMPLIMIENTOS DE LAS POLITICAS Y DIRECTICES INTERNAS",
  "FALTA DE RESPETO",
  "DISCRIMINACION",
  "ROBO, HURTO O EXTRAVIO DE MATERIALES",
  "RIESGOS PARA LA SALUD",
  "SOBORNO/PAGO O RECIBIMIENTO IMPROPIO",
  "FUGA DE INFORMACION",
];
