import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import { NextAuthProvider, ReactQueryProvider } from "@/src/contexts";
import { AppLayout } from "@/src/components";
import theme from "@/src/theme";
import "./globals.css";
import { NotistackProvider } from "@/src/contexts/notistack";
import DataProtectionInfo from "@/src/components/DataProtectionInfo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NotistackProvider />
        <NextAuthProvider>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <ReactQueryProvider>
                <AppLayout>{children}</AppLayout>
              </ReactQueryProvider>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
